# Name of workflow
name: GitHub Workflow Demo
# Whenever a push is detected on this repo
on: [push]

# What will workflow do
jobs:
  # Name of job
  actions_demo:
    # What type of virtual machine do we want it to run on
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello World!"
    - run: ls
